openapi: 3.0.1
info:
  title: Testkube API
  description: >-
    Testkube provides a Kubernetes-native framework for test definition,
    execution and results
  contact:
    email: testkube@kubeshop.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
paths:
  /labels:
    get:
      summary: List labels
      description: list all available labels
      operationId: listLabels
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
                example:
                  app:
                    - backend
                  env:
                    - prod
                  toDelete:
                    - 'yes'
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
