openapi: 3.0.1
info:
  title: Testkube API
  description: >-
    Testkube provides a Kubernetes-native framework for test definition,
    execution and results
  contact:
    email: testkube@kubeshop.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
paths:
  /secrets:
    get:
      parameters:
        - $ref: './components.yaml#/components/parameters/All'
        - $ref: './components.yaml#/components/parameters/Namespace'
      summary: List secrets
      description: List secrets available in cluster
      operationId: listSecrets
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Secret'
        '502':
          description: problem with communicating with kubernetes cluster or git server
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
