openapi: 3.0.1
info:
  title: Testkube Pro API
  description: API for Testkube Pro
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: enterprise-api/1.10.7
paths:
  /organizations:
    get:
      summary: List organizations
      description: List organizations
      operationId: listOrganizations
      parameters:
        - $ref: './components.yaml#/components/parameters/Limit'
      responses:
        '200':
          $ref: './components.yaml#/components/responses/Organizations'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
      security:
        - BearerAuth: []
    post:
      summary: Create new organization
      description: Create organization
      operationId: createOrganization
      requestBody:
        $ref: './components.yaml#/components/requestBodies/Organization'
      responses:
        '200':
          $ref: './components.yaml#/components/responses/Organization'
        '400':
          $ref: './components.yaml#/components/responses/BadRequestError'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
      security:
        - BearerAuth: []
