openapi: 3.0.1
info:
  title: Testkube Pro API
  description: API for Testkube Pro
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: cloud-api/1.10.51
paths:
  /organizations/{id}/team-slug:
    get:
      summary: Checks slug availability
      description: Checks whether given slug is still available.
      operationId: checkTeamSlug
      responses:
        '200':
          $ref: './components.yaml#/components/responses/SlugAvailability'
      security:
        - BearerAuth: []
    parameters:
      - $ref: './components.yaml#/components/parameters/ID'
      - name: slug
        in: query
        description: The slug for which the availability should be checked.
        required: true
        schema:
          type: string
