openapi: 3.0.1
info:
  title: Testkube API
  description: >-
    Testkube provides a Kubernetes-native framework for test definition,
    execution and results
  contact:
    email: testkube@kubeshop.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
paths:
  /uploads:
    post:
      summary: Upload file
      description: Upload file to be used in executions and tests
      operationId: uploads
      requestBody:
        $ref: './components.yaml#/components/requestBodies/UploadsBody'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
            text/yaml:
              schema:
                type: string
        '400':
          description: problem with the input
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: could not upload file
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
