openapi: 3.0.1
info:
  title: Testkube API
  description: >-
    Testkube provides a Kubernetes-native framework for test definition,
    execution and results
  contact:
    email: testkube@kubeshop.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
paths:
  /keymap/triggers:
    get:
      summary: Test triggers keymap
      description: >-
        Returns a keymap (supported/allowed fields) for the test trigger UI
        screen
      operationId: getKeyMap
      responses:
        '200':
          description: successful get operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/TestTriggerKeyMap'
